In [1]:
import numpy as np
import pandas as pd
import math,copy
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('DataExcel.csv')


In [3]:
X_train = data[['size(sq_ft)', 'Bedrooms', 'Floors', 'Age', 'Kitchen', 'Washrooms']].values
y_train = data['Price($)'].values

In [4]:
data.head()

size(sq_ft)  Bedrooms  Floors  Age  Kitchen  Washrooms  Price($)
0         1361         3       2   10        2          3     34135
1         2178         3       1   13        1          2     51326
2         2722         4       1    6        2          2     62349
3         4083         7       3   23        3          5     97845
4         5445         8       2   12        2          6    117645

In [5]:
print(X_train)
print(y_train)

[[1361    3    2   10    2    3]
 [2178    3    1   13    1    2]
 [2722    4    1    6    2    2]
 [4083    7    3   23    3    5]
 [5445    8    2   12    2    6]]
[ 34135  51326  62349  97845 117645]


In [6]:
X_train = (X_train - np.mean(X_train, axis=0)) / np.std(X_train, axis=0)

In [7]:
def compute_cost(x, y, w, b):
    m = x.shape[0]
    cost = 0.0
    for i in range(m):
        f_wb_i = np.dot(x[i], w) + b
        cost= cost + (f_wb_i - y[i]) **2
    cost = cost / (2*m)
    return cost

In [8]:
def compute_gradient(x, y, w, b):
    m,n = x.shape
    dj_dw = np.zeros(n)
    dj_db = 0.0
    for i in range(m):
        err = (np.dot(x[i], w) + b) - y[i]
        for j in range(n):
            dj_dw[j] = dj_dw[j] + err * x[i, j]
        dj_db = dj_db + err
    dj_dw = dj_dw / m
    dj_db = dj_db / m
    return dj_db , dj_dw

In [9]:
def gradient_descent(x, y, w_in, b_in, cost_function, gradient_function, alpha, num_iters):
    J_history = []
    w =  copy.deepcopy(w_in)  #avoid modifying global w within function
    b = b_in
    for i in range(num_iters):

        # Calculate the gradient and update the parameters
        dj_db,dj_dw = gradient_function(x, y, w, b)   ##None

        # Update Parameters using w, b, alpha and gradient
        w = w - alpha * dj_dw               ##None
        b = b - alpha * dj_db
         # Save cost J at each iteration
        if i<10000:      # prevent resource exhaustion 
            J_history.append( cost_function(x, y, w, b))

        # Print cost every at intervals 10 times or as many iterations if < 10
        if i% math.ceil(num_iters / 10) == 0:
            print(f"Iteration {i:4d}: Cost {J_history[-1]:8.2f}   ")
        
    return w, b, J_history

In [10]:
initial_w = [0,0,0,0,0,0]
initial_b = 0
# some gradient descent settings
iterations =10000
alpha = 0.002
# run gradient descent 
w_final, b_final, J_hist = gradient_descent(X_train, y_train, initial_w, initial_b,
                                                    compute_cost, compute_gradient, 
                                                    alpha, iterations)
print(f"b,w found by gradient descent: b= {b_final:0.2f}   w =  {w_final} ")
input = np.array([2800, 4, 1, 6, 2, 2]) ##for customize 
input_normalized = (input - np.mean(data[['size(sq_ft)', 'Bedrooms', 'Floors', 'Age', 'Kitchen', 'Washrooms']].values, axis=0)) / np.std(data[['size(sq_ft)', 'Bedrooms', 'Floors', 'Age', 'Kitchen', 'Washrooms']].values, axis=0)
m,_ = X_train.shape
for i in range(m):
    print(f"prediction: {np.dot(X_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}") ##X_train[i]
print(f"Size in sq_ft is : {input[0]}\nNumber of Bedrooms :{input[1]}\nNumber of Floors : {input[2]}\nAge of the house: {input[3]},\nNumber of Kitchens : {input[4]}\nNumber of washrooms : {input[5]}\nTotal predicted price of the house : {np.dot(input_normalized, w_final) + b_final:0.2f}")

Iteration    0: Cost 3093187327.92   
Iteration 1000: Cost 57511364.70   
Iteration 2000: Cost 4737501.56   
Iteration 3000: Cost 1881223.25   
Iteration 4000: Cost 912065.99   
Iteration 5000: Cost 446916.32   
Iteration 6000: Cost 219256.58   
Iteration 7000: Cost 107602.61   
Iteration 8000: Cost 52813.12   
Iteration 9000: Cost 25922.56   
b,w found by gradient descent: b= 72660.00   w =  [17387.45106854 12735.60189881 -6953.8838874   4459.49304184
  2393.02238426  1277.10088309] 
prediction: 34377.14, target value: 34135
prediction: 51292.69, target value: 51326
prediction: 62146.56, target value: 62349
prediction: 97726.51, target value: 97845
prediction: 117757.09, target value: 117645
Size in sq_ft is : 2800
Number of Bedrooms :4
Number of Floors : 1
Age of the house: 6,
Number of Kitchens : 2
Number of washrooms : 2
Total predicted price of the house : 63083.98
